import Spf from '../../../../public/Assets/Images/divisiLogo/SPF.png';
import Aha from '../../../../public/Assets/Images/divisiLogo/aha.png';
import Bha from '../../../../public/Assets/Images/divisiLogo/bha.png';
import Ceramide from '../../../../public/Assets/Images/divisiLogo/ceramide.png';
import GlycolicAcid from '../../../../public/Assets/Images/divisiLogo/glycolicAcid.png';
import Hyacid from '../../../../public/Assets/Images/divisiLogo/hyacid.png';
import Niacinamide from '../../../../public/Assets/Images/divisiLogo/niacinamide.png';
import Panthenol from '../../../../public/Assets/Images/divisiLogo/panthenol.png';
import Peptides from '../../../../public/Assets/Images/divisiLogo/peptides.png';
import Retinol from '../../../../public/Assets/Images/divisiLogo/retinol2.png';
import salicylicAcid from '../../../../public/Assets/Images/divisiLogo/salicylicAcid.png';

export const DataDivisi = [
        { image: Spf, info: 'SPF', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Aha, info: 'AHA', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Bha, info: 'BHA', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Ceramide, info: 'Ceramide', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: GlycolicAcid, info: 'Glycolic Acid', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Hyacid, info: 'Hyacid', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Niacinamide, info: 'Niacinamide', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Panthenol, info: 'Panthenol', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Peptides, info: 'Peptides', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: Retinol, info: 'Retinol', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
        { image: salicylicAcid, info: 'salicyliAcid', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo ullam ipsum placeat, earum illo. Cupiditate totam, fugiat dolore harum officiis incidunt ipsum similique consequatur non error illo dolores nisi?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid minima accusamus eaque eum dicta culpa molestiae nisi numquam nesciunt quos qui, enim recusandae excepturi dolore blanditiis, iste facere veniam harum.' },
]